# Generated by Django 4.1.4 on 2022-12-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
