# Generated by Django 4.1.4 on 2022-12-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_conatact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatact_us',
            new_name='Contact_us',
        ),
    ]
