# Generated by Django 4.1.4 on 2022-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In stock', 'Instock'), ('Out of stock', 'Out of stock')], max_length=100, null=True),
        ),
    ]
